config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  resources :posts
  resources :tags
  # root :to => 'categories#index'
  #
  # resources :categories do
  #   resources :posts
  # end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  # belongs_to :category
  has_and_belongs_to_many :tags

  validates :title, :presence => true
  validates :contributor, :presence => true
  validates :image, :presence => true
  validates :description, :presence => true

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true

  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
# class CategoriesController < ApplicationController
#   def index
#     @categories = Category.all
#     @post = Post.all
#   end
#
#   def show
#     @category = Category.find(params[:id])
#     @posts = @category.posts
#   end
#
#   def new
#     @category = Category.new
#   end
#
#   def create
#     @category = Category.new(category_params)
#     if @category.save
#       flash[:notice] = "Category successfully added!"
#       redirect_to categories_path
#     else
#       render :new
#     end
#   end
#
#   def edit
#     @category = Category.find(params[:id])
#   end
#
#   def update
#     @category = Category.find(params[:id])
#     if @category.update(category_params)
#       redirect_to categories_path
#     else
#       render :edit
#     end
#   end
#
#   def destroy
#     @category = Category.find(params[:id])
#     @category.destroy
#     redirect_to categories_path
#   end
#
#   private
#   def category_params
#     params.require(:category).permit(:name)
#   end
# end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.all
    # @tags = Tag.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    # @category = Category.find(params[:category_id])
    # @post = @category.posts.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end

    # @category = Category.find(params[:category_id])
    # @post = @category.posts.new(post_params)
    # if @post.save
    #   flash[:notice] = "Post successfully added!"
    #   redirect_to category_path(@post.category)
    # else
    #   render :new
    # end
  end

  def edit
    # @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    @tags = @post.tags
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      @tags = @post.tags
      render :edit
    end
  end
  #
  # def update
  #   @category = Category.find(params[:category_id])
  #   @post = @category.posts.find(params[:id])
  #     if @post.update(post_params)
  #       redirect_to category_path(@category)
  #     else
  #       render :edit
  #     end
  # end
  #
  # def destroy
  #   @category = Category.find(params[:category_id])
  #   @post = Post.find(params[:id])
  #   @post.destroy
  #   redirect_to category_path(@post.category)
  # end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :contributor, :image, :description, :tag_ids => [])
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @posts = Post.all
    @tags = Tag.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    # @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_path(@tag)
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to root_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render "layouts/errors", :object => @category %>

  <%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit 'Submit', class:'btn btn-success' %>
  <% end %>

app/views/categories/edit.html.erb
<h3>Update Category</h3>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class='homepage_title'>
  <h1>Shelter Me</h1>
  <p class='title_font'>creative housing ideas</p>
</div>

<hr>

<div class='container_post'>
  <h3>Posts</h3>
    <% @post.each do |post| %>
    <li><%= post.title %> || posted on <%= post.created_at.strftime("%B %d, %Y") %></li>
    <% end %>
</div>

<hr>

<div class='container_category'>
  <div class='col-md-6'>
    <h3>Categories</h3>
    <ul>
      <% @categories.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
  </div>

  <div class='col-md-6'>
    <div class='homepage_image'>
      <img src="https://www.glen-l.com/designs/house/house-images/dsn-hfc.jpg">
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h3>New Category</h3>

<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= @category.name %> Housing Ideas</h2>
  <p><%= link_to "Update Category", edit_category_path(@category) %></p>
  <p><%= link_to "Delete Category", category_path(@category), :method => 'delete' %></p>
<hr>

<% if @category.posts.any? %>
  <ul>
    <% @category.posts.each do |post| %>
      <li><h4><%= post.title %></h4></li>
      <li>Posted by <%= post.contributor %> on <%= post.created_at.strftime("%B %d, %Y") %></li>
      <li><%= post.description %></li>
      <li><img src='<%= post.image %>'></li>
      <li><%= link_to "Update Post", edit_category_post_path(@category, post) %></li>
      <li><%= link_to "Delete Post", category_post_path(@category, post), :method => 'delete' %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are currently no posts!</p>
<% end %>

<p><%= link_to "Add Post", new_category_post_path(@category) %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h4>Please fix these errors:</h4>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shelter Me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Permanent+Marker|Bad+Script|Reenie+Beanie|Annie+Use+Your+Telescope|Dawning+of+a+New+Day|Over+the+Rainbow' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class='navbar navbar-default'>
      <a class="navbar-brand" href="/">Home</a>
      <ul class='nav navbar-nav'>
        <!-- <li><a href="/posts/new">Add Post</a></li> -->
        <!-- <li><a href="/tags/new">Add Tag</a></li> -->
      </ul>
    </div>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :contributor %>
  <%= f.text_field :contributor %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <h4>Add Tags:</h4>
  <ul>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |b| %>
    <li><%= b.label { b.check_box } %>
    <%= b.object.name %></li>
  <% end %>
  </ul>

  <%= f.submit 'Submit', class:'btn btn-success' %>
<% end %>

app/views/posts/edit.html.erb
<h3>Update Post</h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <h3>All Posts:</h3>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no posts yet.</p>
<% end %>

app/views/posts/new.html.erb
<h3>Add a Post</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<h5>posted by: <%= @post.contributor %> on <%= @post.created_at.strftime("%B %d, %Y") %></h5>
<img src='<%= @post.image %>'>



<p><%= link_to "Edit Post", edit_post_path(@post) %></p>
<p><%= link_to "Delete Post", post_path(@post), :method => 'delete' %></p>

<hr>

<% if @post.tags.any? %>
  <h5>Tags for this post:</h5>

  <ul>
    <% @post.tags.each do |tag| %>
      <li><%= link_to tag.name, tag_path(tag) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tags yet!</p>
<% end %>

app/views/tags/_form.html.erb
<%= render "layouts/errors", :object => @tag %>

<%= form_for @tag do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'Submit', class:'btn btn-success' %>
<% end %>

app/views/tags/edit.html.erb
<h3>Update Tag</h3>

<%= render 'form' %>

app/views/tags/index.html.erb
<% if @tags.any? %>
  <h3>All Tags:</h3>
  <ul>
    <% @tags.each do |tag| %>
      <li><%= link_to tag.name, tag_path(tag) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tags yet.</p>
<% end %>

app/views/tags/new.html.erb
<h3>Add a Tag</h3>

<%= render 'form' %>

app/views/tags/show.html.erb
<h3>Tag name: <%= @tag.name %></h3>

<p><%= link_to "Edit Tag", edit_tag_path(@tag) %></p>

<p><%= link_to "Delete Tag", tag_path(@tag), :method => 'delete' %></p>

<hr>

<% if @tag.posts.any? %>
  <h5>Posts that include this tag:</h5>

  <ul>
    <% @tag.posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no posts that include this tag!</p>
<% end %>